//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volunteer_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application_unit()
        {
            this.Abnormal_event = new HashSet<Abnormal_event>();
            this.Expertises = new HashSet<Expertise>();
            this.Manpower_apply = new HashSet<Manpower_apply>();
            this.Service_period = new HashSet<Service_period>();
            this.Service_period2 = new HashSet<Service_period2>();
            this.Shift_schedule = new HashSet<Shift_schedule>();
            this.Volunteer_list = new HashSet<Volunteer_list>();
        }
    
        public int Application_unit_no { get; set; }
        public string Application_unit1 { get; set; }
        public Nullable<int> Group_no { get; set; }
        public string Application_phone_no { get; set; }
        public string Principal { get; set; }
        public string Principal_phone_no { get; set; }
        public string Application_address { get; set; }
        public string Work_content { get; set; }
        public int Total_volunteers { get; set; }
        public string ImagePath { get; set; }
        public string Work_place { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abnormal_event> Abnormal_event { get; set; }
        public virtual Service_group Service_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expertise> Expertises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manpower_apply> Manpower_apply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_period> Service_period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_period2> Service_period2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shift_schedule> Shift_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Volunteer_list> Volunteer_list { get; set; }
    }
}
