//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volunteer_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Volunteer()
        {
            this.Abnormal_event = new HashSet<Abnormal_event>();
            this.Abnormal_event1 = new HashSet<Abnormal_event>();
            this.Volunteer_list = new HashSet<Volunteer_list>();
            this.Activity_Schedule = new HashSet<Activity_Schedule>();
            this.Shift_schedule = new HashSet<Shift_schedule>();
            this.Activity1 = new HashSet<Activity1>();
            this.Educations = new HashSet<Education>();
            this.Experiences = new HashSet<Experience>();
            this.Expertise2 = new HashSet<Expertise2>();
            this.Leaders1 = new HashSet<Leaders1>();
            this.Service_Group1 = new HashSet<Service_Group1>();
            this.Service_period2 = new HashSet<Service_period2>();
        }
    
        public int Volunteer_no { get; set; }
        public string Chinese_name { get; set; }
        public string English_name { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string IDcrad_no { get; set; }
        public string Medical_record_no { get; set; }
        public int Identity_type { get; set; }
        public int Seniority { get; set; }
        public Nullable<System.DateTime> Join_date { get; set; }
        public Nullable<System.DateTime> Leave_date { get; set; }
        public string Leave_reason { get; set; }
        public Nullable<int> Phone_no { get; set; }
        public Nullable<int> Mobile_no { get; set; }
        public string Vest_no { get; set; }
        public Nullable<int> Postal_code { get; set; }
        public string Address { get; set; }
        public string Education { get; set; }
        public Nullable<int> Lssuing_unit_no { get; set; }
        public string Service_manual_no { get; set; }
        public string Personality_scale { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abnormal_event> Abnormal_event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abnormal_event> Abnormal_event1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Volunteer_list> Volunteer_list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Schedule> Activity_Schedule { get; set; }
        public virtual Identity_type Identity_type1 { get; set; }
        public virtual Lssuing_unit Lssuing_unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shift_schedule> Shift_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity1> Activity1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Educations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experience> Experiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expertise2> Expertise2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leaders1> Leaders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Group1> Service_Group1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_period2> Service_period2 { get; set; }
    }
}
