//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volunteer_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expertise
    {
        public int Primary_key { get; set; }
        public int Application_unit_no { get; set; }
        public int Expertise_no { get; set; }
    
        public virtual Application_unit Application_unit { get; set; }
        public virtual Expertise1 Expertise1 { get; set; }
    }
}
